language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

script: perl Makefile.PL && make && make test

after_failure: cat /home/travis/.cpanm/build.log

branches:
  only:
    - master